[workspace]
resolver = "2"

members = [
    "server"
]

[workspace.dependencies]
lsp-server = "=0.7.9"
lsp-types = "=0.97.0"
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"
